### ISSUE TITLE
[10%] Create HTML pages for user interface (II)

### ISSUE THREAD

**Issue by vasopikof** [CCPX-system/CCPX-application-ref.-only-#10]

**Comment by FlorenceMei** [comment]
Status: working

**Comment by FlorenceMei** [comment]
1) OFFER STREAMING (2 pages)

Worker:
Status:
Commit:

2) LIST OF SELLERS (2d page) 

Worker:
Status:
Commit:

3) COMPANY'S PRESENTATION (2) 

Worker:
Status:
Commit:

4) MY ACCOUNT

Worker:
Status:
Commit:

5) EDIT PROFIL

Worker:
Status:
Commit:

6) MY POINTS

Worker:
Status:
Commit:

7) LOGIN IN COMPANY

Worker:
Status:
Commit:

8) REGISTER IN COMPANY

Worker:
Status:
Commit:

9) EXCHANGE CENTER

Worker:
Status:
Commit:

10) MAKE AN OFFER EXCHANGES FOUND

Worker:
Status:
Commit:

11) RECENT ACTIVITY 

Worker:
Status:
Commit:

12) EXCHANGE RATE EVOLUTION 

Worker:
Status:
Commit:

13) USER PROFIL

Worker:
Status:
Commit:

14) FIND AN USER 

Worker:
Status:
Commit:

15) EXCHANGES STATUS 

Worker:
Status:
Commit:

16) SELECT AN USER 

Worker:
Status:
Commit:

17) EDIT YOUR OFFER 

Worker:
Status:
Commit:

18) EXCHANGE HISTORY

Worker:
Status:
Commit:
