### ISSUE TITLE
[15%] Create HTML pages for seller interface

### ISSUE THREAD

**Issue by whg7** [CCPX-system/CCPX-application-ref.-only-#14]

**Comment by quentinlegaux** [comment]
**Pages from seller group (protype 8.0)**

1. advanced-search
2. business_information
3. delete_advertissement
4. exchange_points
5. exchange_rate
6. find_password
7. home_page
8. index
9. intelligent_query
10. login
11. manage_advertisement
12. modify_advertisement
13. modify_information
14. pay_advertisement_fee
15. pay_member_fee
16. registration
17. start
18. trading_chart_points
19. trading_chart_times
20. upload_advertisement
21. view_advertisement

_this list of page is maybe not complete..._

**Comment by vasopikof** [comment]
@FlorenceMei you removed this from third sprint, mean this belong to 4th sprint ?
